name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.1'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Run lint and tests
        run: npm run lint && npm run test
      - name: Build package
        run: npm run build
      - name: Authenticate with NPM
        run: |
          npm set //npm.pkg.github.com/:_authToken=${NPM_TOKEN}
          npm set //npm.pkg.github.com/:username="lopes-software"
          npm set //npm.pkg.github.com/:email="flopes.alexandre@gmail.com"
          npm set //npm.pkg.github.com/:_password=${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish package on NPM
        run: npm publish
        
